# Generated by Django 3.1.1 on 2021-01-08 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_starter_app.languagename')),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='django_starter_app.languagename')),
                ('word_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='django_starter_app.word')),
            ],
        ),
    ]
