# Generated by Django 3.1.1 on 2021-01-08 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_starter_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='language_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_translation', to='django_starter_app.languagename'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='word_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_translation', to='django_starter_app.word'),
        ),
        migrations.AlterField(
            model_name='word',
            name='language_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word', to='django_starter_app.languagename'),
        ),
    ]
