# Generated by Django 3.1.1 on 2021-01-08 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_starter_app', '0002_auto_20210108_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='language_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='django_starter_app.languagename'),
        ),
    ]
